//
//  SampleResponse.swift
//  Tests iOS
//
//  Created by Dot Indonesia on 03/02/22.
//

import Foundation

class SampleResponse {
    
    static func moviesList() -> String {
        return """
            {
            "page": 1,
            "results": [
                {
                    "adult": false,
                    "backdrop_path": "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
                    "genre_ids": [
                        28,
                        12,
                        878
                    ],
                    "id": 634649,
                    "original_language": "en",
                    "original_title": "Spider-Man: No Way Home",
                    "overview": "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
                    "popularity": 16819.659,
                    "poster_path": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                    "release_date": "2021-12-15",
                    "title": "Spider-Man: No Way Home",
                    "video": false,
                    "vote_average": 8.4,
                    "vote_count": 6856
                }
            ],
            "total_pages": 2,
            "total_results": 100
        }
""";
    }
    
    static func similiarMovies() -> String {
        return """
            {
                "page": 1,
                "results": [
                    {
                        "adult": false,
                        "backdrop_path": "/aZBZtLCM90QHDCuZFR6oc4NXCWu.jpg",
                        "genre_ids": [
                            28,
                            12,
                            878
                        ],
                        "id": 100402,
                        "title": "Captain America: The Winter Soldier",
                        "original_language": "en",
                        "original_title": "Captain America: The Winter Soldier",
                        "overview": "After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.",
                        "popularity": 71.418,
                        "poster_path": "/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg",
                        "release_date": "2014-03-20",
                        "video": false,
                        "vote_average": 7.68,
                        "vote_count": 15665
                    }
                ],
                "total_pages": 500,
                "total_results": 10000
            }
            """;
    }
    
    static func peopleList() -> String {
        return """
            {
                "id": 634649,
                "cast": [
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1136406,
                        "known_for_department": "Acting",
                        "name": "Tom Holland",
                        "original_name": "Tom Holland",
                        "popularity": 118.175,
                        "profile_path": "/2qhIDp44cAqP2clOgt2afQI07X8.jpg",
                        "cast_id": 1,
                        "character": "Peter Parker / Spider-Man",
                        "credit_id": "5d8e28d38289a0000fcc32f9",
                        "order": 0
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 505710,
                        "known_for_department": "Acting",
                        "name": "Zendaya",
                        "original_name": "Zendaya",
                        "popularity": 66.642,
                        "profile_path": "/jHWlWOasiqKS8JI40g9GDH5X6AL.jpg",
                        "cast_id": 54,
                        "character": "Michelle 'MJ' Jones",
                        "credit_id": "5fd968c09408ec003cdd0557",
                        "order": 1
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 71580,
                        "known_for_department": "Acting",
                        "name": "Benedict Cumberbatch",
                        "original_name": "Benedict Cumberbatch",
                        "popularity": 34.379,
                        "profile_path": "/fBEucxECxGLKVHBznO0qHtCGiMO.jpg",
                        "cast_id": 33,
                        "character": "Stephen Strange / Doctor Strange",
                        "credit_id": "5f7f51e42f3b170035f3a821",
                        "order": 2
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1649152,
                        "known_for_department": "Acting",
                        "name": "Jacob Batalon",
                        "original_name": "Jacob Batalon",
                        "popularity": 27.103,
                        "profile_path": "/53YhaL4xw4Sb1ssoHkeSSBaO29c.jpg",
                        "cast_id": 69,
                        "character": "Ned Leeds",
                        "credit_id": "6124200e4a52f8005dd04318",
                        "order": 3
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 15277,
                        "known_for_department": "Acting",
                        "name": "Jon Favreau",
                        "original_name": "Jon Favreau",
                        "popularity": 14.824,
                        "profile_path": "/8MtRRnEHaBSw8Ztdl8saXiw1egP.jpg",
                        "cast_id": 82,
                        "character": "Harold 'Happy' Hogan",
                        "credit_id": "612450fa2dc44e0045c8df84",
                        "order": 4
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 134,
                        "known_for_department": "Acting",
                        "name": "Jamie Foxx",
                        "original_name": "Jamie Foxx",
                        "popularity": 26.036,
                        "profile_path": "/hPwCMEq6jLAidsXAX5BfoYgIfg2.jpg",
                        "cast_id": 68,
                        "character": "Max Dillon / Electro",
                        "credit_id": "61241f30c5c1ef005c08f777",
                        "order": 5
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 5293,
                        "known_for_department": "Acting",
                        "name": "Willem Dafoe",
                        "original_name": "Willem Dafoe",
                        "popularity": 36.482,
                        "profile_path": "/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg",
                        "cast_id": 81,
                        "character": "Norman Osborn / Green Goblin",
                        "credit_id": "612450a4886348005eb353a7",
                        "order": 6
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 658,
                        "known_for_department": "Acting",
                        "name": "Alfred Molina",
                        "original_name": "Alfred Molina",
                        "popularity": 16.644,
                        "profile_path": "/nJo91Czesn6z0d0pkfbDoVZY3sg.jpg",
                        "cast_id": 66,
                        "character": "Dr. Otto Octavius / Doctor Octopus",
                        "credit_id": "61241e3053466100452f0942",
                        "order": 7
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 30082,
                        "known_for_department": "Acting",
                        "name": "Benedict Wong",
                        "original_name": "Benedict Wong",
                        "popularity": 27.69,
                        "profile_path": "/ukmfsl59Isvn9odgzMWBidA3cmt.jpg",
                        "cast_id": 79,
                        "character": "Wong",
                        "credit_id": "61244f322dc44e007e586c24",
                        "order": 8
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1291350,
                        "known_for_department": "Acting",
                        "name": "Tony Revolori",
                        "original_name": "Tony Revolori",
                        "popularity": 14.402,
                        "profile_path": "/ouuo4ulVO9j6T8JixFp4lWTVdtd.jpg",
                        "cast_id": 71,
                        "character": "Eugene 'Flash' Thompson",
                        "credit_id": "61242cd46f53e1005c9a5d81",
                        "order": 9
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 3141,
                        "known_for_department": "Acting",
                        "name": "Marisa Tomei",
                        "original_name": "Marisa Tomei",
                        "popularity": 25.505,
                        "profile_path": "/pP0J79KUzPPjW4QO42iF4KKM7C6.jpg",
                        "cast_id": 56,
                        "character": "May Parker",
                        "credit_id": "5fd968d6db952d003e815de4",
                        "order": 10
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 37625,
                        "known_for_department": "Acting",
                        "name": "Andrew Garfield",
                        "original_name": "Andrew Garfield",
                        "popularity": 56.63,
                        "profile_path": "/beO5YvbTjrr5yy8hW26KVDMSr35.jpg",
                        "cast_id": 159,
                        "character": "Peter Parker / Spider-Man",
                        "credit_id": "61b891dd1f3319006121ecd1",
                        "order": 11
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 2219,
                        "known_for_department": "Acting",
                        "name": "Tobey Maguire",
                        "original_name": "Tobey Maguire",
                        "popularity": 37.516,
                        "profile_path": "/ncF4HivY2W6SQW5dEP3N3I4mfT0.jpg",
                        "cast_id": 160,
                        "character": "Peter Parker / Spider-Man",
                        "credit_id": "61b891e643999b0064592e99",
                        "order": 12
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 1265629,
                        "known_for_department": "Acting",
                        "name": "Angourie Rice",
                        "original_name": "Angourie Rice",
                        "popularity": 29.053,
                        "profile_path": "/5zf2Cr4p7KQEcSv7ZPSLfT2R7mR.jpg",
                        "cast_id": 70,
                        "character": "Betty Brant",
                        "credit_id": "6124208e88634800456f6fa1",
                        "order": 13
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 457386,
                        "known_for_department": "Acting",
                        "name": "Arian Moayed",
                        "original_name": "Arian Moayed",
                        "popularity": 4.796,
                        "profile_path": "/vL5eKRzDGdMyQJpzODD6lfg42LV.jpg",
                        "cast_id": 89,
                        "character": "Agent Cleary",
                        "credit_id": "612486f6501cf20075acbe55",
                        "order": 14
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 17420,
                        "known_for_department": "Acting",
                        "name": "Paula Newsome",
                        "original_name": "Paula Newsome",
                        "popularity": 11.328,
                        "profile_path": "/b6SdnIsuPKv6MCJwGELycUYbfss.jpg",
                        "cast_id": 80,
                        "character": "MIT Assistant Vice Chancellor",
                        "credit_id": "6124501c0102c90024085e81",
                        "order": 15
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 500427,
                        "known_for_department": "Acting",
                        "name": "Hannibal Buress",
                        "original_name": "Hannibal Buress",
                        "popularity": 10.057,
                        "profile_path": "/mcw3Orbg4vbALXTVG4hriZjH1sj.jpg",
                        "cast_id": 72,
                        "character": "Coach Wilson",
                        "credit_id": "61242cdf534661005cd03e57",
                        "order": 16
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 41089,
                        "known_for_department": "Acting",
                        "name": "Martin Starr",
                        "original_name": "Martin Starr",
                        "popularity": 16.116,
                        "profile_path": "/gNyCdend3C5gY3ucq42Zt3swfg2.jpg",
                        "cast_id": 75,
                        "character": "Mr. Harrington",
                        "credit_id": "61242d810102c9002407fd2a",
                        "order": 17
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 65920,
                        "known_for_department": "Acting",
                        "name": "J.B. Smoove",
                        "original_name": "J.B. Smoove",
                        "popularity": 13.633,
                        "profile_path": "/691r7OL0R9TaR7SaqR6AnKVLUUu.jpg",
                        "cast_id": 74,
                        "character": "Mr. Dell",
                        "credit_id": "61242cf0886348007e380021",
                        "order": 18
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 18999,
                        "known_for_department": "Acting",
                        "name": "J.K. Simmons",
                        "original_name": "J.K. Simmons",
                        "popularity": 29.166,
                        "profile_path": "/7kIiPojgSVNRXb5z0hiijcD5LJ6.jpg",
                        "cast_id": 67,
                        "character": "J. Jonah Jameson",
                        "credit_id": "61241ee1d6c300007e705c88",
                        "order": 19
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 7026,
                        "known_for_department": "Acting",
                        "name": "Rhys Ifans",
                        "original_name": "Rhys Ifans",
                        "popularity": 21.858,
                        "profile_path": "/g8EUs8r1ECh9plKtrxBparsxlZ1.jpg",
                        "cast_id": 161,
                        "character": "Dr. Curt Connors / The Lizard",
                        "credit_id": "61b8b80bcb75d1001c083bcf",
                        "order": 20
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 23458,
                        "known_for_department": "Acting",
                        "name": "Charlie Cox",
                        "original_name": "Charlie Cox",
                        "popularity": 21.812,
                        "profile_path": "/jBHDZ8MA4I7krNQx4IfqdfPfleD.jpg",
                        "cast_id": 163,
                        "character": "Matt Murdock",
                        "credit_id": "61b8b840c616ac00668a2e51",
                        "order": 21
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 19159,
                        "known_for_department": "Acting",
                        "name": "Thomas Haden Church",
                        "original_name": "Thomas Haden Church",
                        "popularity": 10.227,
                        "profile_path": "/VP6VDYL0OEDwSbTRysiJ0kAGxI.jpg",
                        "cast_id": 162,
                        "character": "Flint Marko / Sandman",
                        "credit_id": "61b8b82585005d009397e0ea",
                        "order": 22
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 2996576,
                        "known_for_department": "Acting",
                        "name": "Haroon Kahn",
                        "original_name": "Haroon Kahn",
                        "popularity": 0.748,
                        "profile_path": null,
                        "cast_id": 164,
                        "character": "Apprentice",
                        "credit_id": "61bb4279ac6c7900884fb546",
                        "order": 23
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 2104193,
                        "known_for_department": "Acting",
                        "name": "Emily Lue Fong",
                        "original_name": "Emily Lue Fong",
                        "popularity": 3.963,
                        "profile_path": null,
                        "cast_id": 165,
                        "character": "Apprentice",
                        "credit_id": "61bb4282873f00001b1b4fc2",
                        "order": 24
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 3353015,
                        "known_for_department": "Acting",
                        "name": "Mary Rivera",
                        "original_name": "Mary Rivera",
                        "popularity": 1.02,
                        "profile_path": null,
                        "cast_id": 186,
                        "character": "Ned's Lola",
                        "credit_id": "61bfdd62d19a330095445166",
                        "order": 25
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1651953,
                        "known_for_department": "Acting",
                        "name": "Rudy Eisenzopf",
                        "original_name": "Rudy Eisenzopf",
                        "popularity": 1.4,
                        "profile_path": "/1pDV75qlQwWZ7wLWoE5zenedYBe.jpg",
                        "cast_id": 166,
                        "character": "Arena Bystander",
                        "credit_id": "61bb429b894ed6001ce9b02c",
                        "order": 26
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 3353017,
                        "known_for_department": "Acting",
                        "name": "Kathleen Cardoso",
                        "original_name": "Kathleen Cardoso",
                        "popularity": 1.715,
                        "profile_path": null,
                        "cast_id": 190,
                        "character": "Arena Bystander",
                        "credit_id": "61bfde09105611004139a4be",
                        "order": 27
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3353016,
                        "known_for_department": "Acting",
                        "name": "Jonathan Sam",
                        "original_name": "Jonathan Sam",
                        "popularity": 0.6,
                        "profile_path": null,
                        "cast_id": 189,
                        "character": "Arena Bystander",
                        "credit_id": "61bfddf213af5f00420857e3",
                        "order": 28
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3353020,
                        "known_for_department": "Acting",
                        "name": "Andrew Dunlap",
                        "original_name": "Andrew Dunlap",
                        "popularity": 1.456,
                        "profile_path": null,
                        "cast_id": 191,
                        "character": "Dad in Car",
                        "credit_id": "61bfdeb572c13e001c0a5fde",
                        "order": 29
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1455813,
                        "known_for_department": "Acting",
                        "name": "Ben VanderMey",
                        "original_name": "Ben VanderMey",
                        "popularity": 1.66,
                        "profile_path": "/lkPNTxvIiV0WtBVOV8DbLiCSp0c.jpg",
                        "cast_id": 167,
                        "character": "Man in Car",
                        "credit_id": "61bb42c113af5f004200180d",
                        "order": 30
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3353021,
                        "known_for_department": "Acting",
                        "name": "Zany Dunlap",
                        "original_name": "Zany Dunlap",
                        "popularity": 0.802,
                        "profile_path": null,
                        "cast_id": 192,
                        "character": "Mom in Car",
                        "credit_id": "61bfdec1c4ad590042457923",
                        "order": 31
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3353022,
                        "known_for_department": "Acting",
                        "name": "B. Clutch Dunlap",
                        "original_name": "B. Clutch Dunlap",
                        "popularity": 0.728,
                        "profile_path": null,
                        "cast_id": 193,
                        "character": "Kid in Car",
                        "credit_id": "61bfdecd105611001ccc7e3f",
                        "order": 32
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3353024,
                        "known_for_department": "Acting",
                        "name": "Minnah Dunlap",
                        "original_name": "Minnah Dunlap",
                        "popularity": 1.07,
                        "profile_path": null,
                        "cast_id": 194,
                        "character": "Kid in Car",
                        "credit_id": "61bfdf72d14443004148072a",
                        "order": 33
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 168875,
                        "known_for_department": "Acting",
                        "name": "Gary Weeks",
                        "original_name": "Gary Weeks",
                        "popularity": 8.275,
                        "profile_path": "/n4taftpteF6qUTeYRDkdGPHC58.jpg",
                        "cast_id": 168,
                        "character": "Agent Foster",
                        "credit_id": "61bb42ced2f5b50041b2572b",
                        "order": 34
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1460925,
                        "known_for_department": "Acting",
                        "name": "Gregory Konow",
                        "original_name": "Gregory Konow",
                        "popularity": 2.59,
                        "profile_path": "/k3Zu0epkGox4kaWOTq8dQccab3w.jpg",
                        "cast_id": 169,
                        "character": "Donut Shop Boss",
                        "credit_id": "61bb42dcd2f5b50092f5aae0",
                        "order": 35
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 2933171,
                        "known_for_department": "Acting",
                        "name": "Carol Anne Dines",
                        "original_name": "Carol Anne Dines",
                        "popularity": 0.84,
                        "profile_path": null,
                        "cast_id": 195,
                        "character": "Donut Shop Waitress",
                        "credit_id": "61bfe3451f3319008d4c9855",
                        "order": 36
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 2231998,
                        "known_for_department": "Acting",
                        "name": "Anisa Nyell Johnson",
                        "original_name": "Anisa Nyell Johnson",
                        "popularity": 1.533,
                        "profile_path": "/2hXRw4Snt6fs5xZebcmcyIM0Wp9.jpg",
                        "cast_id": 175,
                        "character": "School Security Guard",
                        "credit_id": "61bee4f609ed8f00407e3bb9",
                        "order": 37
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3353038,
                        "known_for_department": "Acting",
                        "name": "Willie Burton",
                        "original_name": "Willie Burton",
                        "popularity": 0.972,
                        "profile_path": null,
                        "cast_id": 196,
                        "character": "May's Neighbor",
                        "credit_id": "61bfe429ef9d72008a991834",
                        "order": 38
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 2486882,
                        "known_for_department": "Acting",
                        "name": "Mallory Hoff",
                        "original_name": "Mallory Hoff",
                        "popularity": 0.6,
                        "profile_path": null,
                        "cast_id": 176,
                        "character": "Reporter",
                        "credit_id": "61bee50b297338006b48f8ec",
                        "order": 39
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 146024,
                        "known_for_department": "Acting",
                        "name": "Greg Clarkson",
                        "original_name": "Greg Clarkson",
                        "popularity": 0.84,
                        "profile_path": null,
                        "cast_id": 177,
                        "character": "Reporter",
                        "credit_id": "61bee515d371970066b9cd44",
                        "order": 40
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 1613974,
                        "known_for_department": "Acting",
                        "name": "Regina Ting Chen",
                        "original_name": "Regina Ting Chen",
                        "popularity": 5.825,
                        "profile_path": "/7Lqwq6UYbZd7XyMujUKUVUHGSIb.jpg",
                        "cast_id": 178,
                        "character": "Reporter",
                        "credit_id": "61bee51e014325004333e825",
                        "order": 41
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3144298,
                        "known_for_department": "Acting",
                        "name": "Robert Mitchel Owenby",
                        "original_name": "Robert Mitchel Owenby",
                        "popularity": 0.6,
                        "profile_path": "/ttalMWtp4WH6U0n82nOBdoYVYiL.jpg",
                        "cast_id": 179,
                        "character": "Daily Bugle Lackey",
                        "credit_id": "61bee52d0443c9006007d99b",
                        "order": 42
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 1347386,
                        "known_for_department": "Acting",
                        "name": "Glenn Keogh",
                        "original_name": "Glenn Keogh",
                        "popularity": 7.828,
                        "profile_path": "/amv7HimTqvhmVqko9oKNYeHINvx.jpg",
                        "cast_id": 180,
                        "character": "British Reporter",
                        "credit_id": "61bee539d19a3300418c1214",
                        "order": 43
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 2044224,
                        "known_for_department": "Acting",
                        "name": "Paris Benjamin",
                        "original_name": "Paris Benjamin",
                        "popularity": 0.6,
                        "profile_path": "/xDQyGetUDUehJvZquY2gbFb7Lks.jpg",
                        "cast_id": 181,
                        "character": "British Anchor",
                        "credit_id": "61bee5476a300b001d98c8af",
                        "order": 44
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 1370799,
                        "known_for_department": "Acting",
                        "name": "Jwaundace Candece",
                        "original_name": "Jwaundace Candece",
                        "popularity": 2.247,
                        "profile_path": null,
                        "cast_id": 182,
                        "character": "Damage Control Agent",
                        "credit_id": "61bee554b0040a001c13f8dc",
                        "order": 45
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 1382356,
                        "known_for_department": "Acting",
                        "name": "Taylor St. Clair",
                        "original_name": "Taylor St. Clair",
                        "popularity": 1.4,
                        "profile_path": null,
                        "cast_id": 183,
                        "character": "Protestor",
                        "credit_id": "61bee56413af5f0063120ac3",
                        "order": 46
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 1945694,
                        "known_for_department": "Acting",
                        "name": "Gabriella Cila",
                        "original_name": "Gabriella Cila",
                        "popularity": 3.655,
                        "profile_path": "/e4Gya1ymo9btw3rziOVlxl1Ju6v.jpg",
                        "cast_id": 184,
                        "character": "Crowd Member",
                        "credit_id": "61bee57fd19a3300418c125f",
                        "order": 47
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3352136,
                        "known_for_department": "Acting",
                        "name": "Darnell Appling",
                        "original_name": "Darnell Appling",
                        "popularity": 0.661,
                        "profile_path": null,
                        "cast_id": 185,
                        "character": "Crowd Member",
                        "credit_id": "61bee58e105611001ccaeb79",
                        "order": 48
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3353039,
                        "known_for_department": "Acting",
                        "name": "Rolando Fernandez",
                        "original_name": "Rolando Fernandez",
                        "popularity": 1.052,
                        "profile_path": null,
                        "cast_id": 197,
                        "character": "Crowd Member",
                        "credit_id": "61bfe4d9fcadb40095c3fa09",
                        "order": 49
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3353041,
                        "known_for_department": "Acting",
                        "name": "Edward Force",
                        "original_name": "Edward Force",
                        "popularity": 0.695,
                        "profile_path": null,
                        "cast_id": 198,
                        "character": "Donut Shop Patron",
                        "credit_id": "61bfe53bef9d72008a991b3d",
                        "order": 50
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3347286,
                        "known_for_department": "Acting",
                        "name": "Michael Le",
                        "original_name": "Michael Le",
                        "popularity": 0.732,
                        "profile_path": null,
                        "cast_id": 199,
                        "character": "Guy with Phone",
                        "credit_id": "61bfe5d6f29d660099553794",
                        "order": 51
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3353044,
                        "known_for_department": "Acting",
                        "name": "Dean Meminger",
                        "original_name": "Dean Meminger",
                        "popularity": 0.6,
                        "profile_path": null,
                        "cast_id": 200,
                        "character": "NY1 Reporter",
                        "credit_id": "61bfe60c0443c9001c14d8c5",
                        "order": 52
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 3353045,
                        "known_for_department": "Acting",
                        "name": "Frederick A. Brown",
                        "original_name": "Frederick A. Brown",
                        "popularity": 1.388,
                        "profile_path": null,
                        "cast_id": 201,
                        "character": "Fred the Janitor",
                        "credit_id": "61bfe665a284eb0042ed7c2f",
                        "order": 53
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 2627590,
                        "known_for_department": "Acting",
                        "name": "Cristo Fernández",
                        "original_name": "Cristo Fernández",
                        "popularity": 4.231,
                        "profile_path": "/xAZwaVQ1HLbNkLDLqQAUoXUmA6u.jpg",
                        "cast_id": 172,
                        "character": "Bartender",
                        "credit_id": "61bbd374d2f5b50041b36fa0",
                        "order": 54
                    },
                    {
                        "adult": false,
                        "gender": 0,
                        "id": 190611,
                        "known_for_department": "Acting",
                        "name": "Clay Savage",
                        "original_name": "Clay Savage",
                        "popularity": 0.968,
                        "profile_path": null,
                        "cast_id": 202,
                        "character": "Suit Voice (voice)",
                        "credit_id": "61bfe688a84ff7008d2b5155",
                        "order": 55
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 2524,
                        "known_for_department": "Acting",
                        "name": "Tom Hardy",
                        "original_name": "Tom Hardy",
                        "popularity": 34.689,
                        "profile_path": "/sOi4UZxflV07E7QXUaJTHROGlPU.jpg",
                        "cast_id": 170,
                        "character": "Eddie Brock / Venom (uncredited)",
                        "credit_id": "61bb4362e72fe800615f702e",
                        "order": 57
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 3260137,
                        "known_for_department": "Acting",
                        "name": "Jay Karales",
                        "original_name": "Jay Karales",
                        "popularity": 0.6,
                        "profile_path": "/dEHJznSQQ9rbpjZPl2MGu2WArUb.jpg",
                        "cast_id": 212,
                        "character": "Bodega Customer (uncredited)",
                        "credit_id": "61c155bd21621d001b297123",
                        "order": 58
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 131,
                        "known_for_department": "Acting",
                        "name": "Jake Gyllenhaal",
                        "original_name": "Jake Gyllenhaal",
                        "popularity": 22.952,
                        "profile_path": "/oA6fp6SQBQQWZEzn4NfY3E8mJhV.jpg",
                        "cast_id": 217,
                        "character": "Mysterio / Quentin Beck (archive footage) (uncredited)",
                        "credit_id": "61e3658cc1606a0042be1a11",
                        "order": 59
                    }
                ],
                "crew": [
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 2519,
                        "known_for_department": "Costume & Make-Up",
                        "name": "Sanja Milković Hays",
                        "original_name": "Sanja Milković Hays",
                        "popularity": 4.106,
                        "profile_path": null,
                        "credit_id": "61d92db99824c8001c46fa27",
                        "department": "Costume & Make-Up",
                        "job": "Costume Design"
                    },
                    {
                        "adult": false,
                        "gender": 1,
                        "id": 7232,
                        "known_for_department": "Production",
                        "name": "Sarah Halley Finn",
                        "original_name": "Sarah Halley Finn",
                        "popularity": 10.585,
                        "profile_path": "/pI3OhmnHhXLEwuv0Vq6qJHivCJA.jpg",
                        "credit_id": "5eebb0f8db4ed60036cab559",
                        "department": "Production",
                        "job": "Casting"
                    },
                    {
                        "adult": false,
                        "gender": 2,
                        "id": 7624,
                        "known_for_department": "Writing",
                        "name": "Stan Lee",
                        "original_name": "Stan Lee",
                        "popularity": 16.421,
                        "profile_path": "/kKeyWoFtTqOPsbmwylNHmuB3En9.jpg",
                        "credit_id": "5d8f9a8c66a7c30019897e4b",
                        "department": "Writing",
                        "job": "Characters"
                    }
                ]
            }
            """;
    }
    
    
    static func moviesData() -> MovieResponse {
        let json = SampleResponse.moviesList().data(using: .utf8)!
        let movies = try! JSONDecoder().decode(MovieResponse.self, from: json)
        return movies
    }
    
}
